### ISSUE TITLE
Release 1.4.0 is not building on Linux before Swift 6

### ISSUE THREAD

**Issue by vsarunas** [swiftlang/swift-docc-plugin#92]
```
error: fatalError
/tmp/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SharedPackagePluginExtensions/PackageManager+getSymbolGraphsForDocC.swift:74:64: error: value of type 'NSLock' has no member 'withLock'
        let targetSymbolGraphs = try symbolGraphGenerationLock.withLock {
```

```
$ swift --version
Swift version 5.10 (swift-5.10-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by hassila** [comment]
Ping @d-ronnqvist

**Comment by finagolfin** [comment]
I'm [seeing this on my Android CI too](https://github.com/finagolfin/swift-android-sdk/actions/runs/10523050901/job/29156992060#step:14:59), can confirm that the just-released 1.4.0 tag broke building this plugin with Swift 5.10.1 on linux:
```
swift-nio/.build/checkouts/swift-docc-plugin/Plugins/Swift-DocC Convert/Symbolic Links/SharedPackagePluginExtensions/PackageManager+getSymbolGraphsForDocC.swift:74:64: error: value of type 'NSLock' has no member 'withLock'
        let targetSymbolGraphs = try symbolGraphGenerationLock.withLock {
                                     ~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~
```
It [works fine with the upcoming Swift 6](https://github.com/finagolfin/swift-android-sdk/actions/runs/10523050901/job/29156992982#step:14:41) and 6.1.

**Comment by d-ronnqvist** [comment]
This should be resolved in release 1.4.1 now.

**Comment by hassila** [comment]
Super, thanks @d-ronnqvist !

**Comment by thomasvl** [comment]
I think we're still seeing problems with Swift 5.8.1 on linux:

https://github.com/apple/swift-protobuf/actions/runs/10529237017/job/29178134702?pr=1694

**Comment by d-ronnqvist** [comment]
That looks like a different failure than before.

**Comment by d-ronnqvist** [comment]
I'm on vacation next week, away from a computer, but I can look at this when I get back if no one else has fixed this by then.
